# Generated by Django 6.0.6 on 2026-06-22 02:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('imagen_portada', models.ImageField(upload_to='ciudades/portadas/')),
                ('latitud_centro', models.FloatField(help_text='Latitud para centrar el mapa de la ciudad')),
                ('longitud_centro', models.FloatField(help_text='Longitud para centrar el mapa de la ciudad')),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('es_protagonista', models.BooleanField(default=False)),
                ('es_turista', models.BooleanField(default=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CircuitoCreativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('distancia_km', models.DecimalField(decimal_places=2, help_text='Distancia en kilómetros', max_digits=5)),
                ('duracion_estimada', models.CharField(help_text="Ej: '2 horas', '45 minutos'", max_length=50)),
                ('dificultad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Baja', max_length=10)),
                ('imagen_mapa', models.ImageField(blank=True, help_text='Imagen opcional estática de la ruta', null=True, upload_to='circuitos/mapas/')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuitos', to='circuitos.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Protagonista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('Artesania', 'Artesanía / Pintura'), ('Gastronomia', 'Gastronomía Tradicional'), ('Hospedaje', 'Hospedaje Familiar'), ('Servicios Turisticos', 'Servicios Turísticos y Guía'), ('Otro', 'Otro')], default='Artesania', max_length=30)),
                ('telefono', models.CharField(max_length=20)),
                ('redes_sociales', models.JSONField(blank=True, default=dict, help_text="JSON con redes, ej: {'facebook': '...', 'instagram': '...'}")),
                ('verificado', models.BooleanField(default=False, help_text='Verificación oficial por la Red de Ciudades Creativas')),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protagonistas', to='circuitos.ciudad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='protagonista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en Córdobas (NIO)', max_digits=10)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('es_emblematico', models.BooleanField(default=False, help_text='Marcar si es un producto/servicio emblemático de la ciudad')),
                ('protagonista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='circuitos.protagonista')),
            ],
            options={
                'verbose_name': 'Producto o Servicio',
                'verbose_name_plural': 'Productos y Servicios',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('lugar', models.CharField(help_text='Dirección física del evento', max_length=200)),
                ('latitud', models.FloatField(blank=True, help_text='Ubicación en el mapa (latitud)', null=True)),
                ('longitud', models.FloatField(blank=True, help_text='Ubicación en el mapa (longitud)', null=True)),
                ('imagen', models.ImageField(upload_to='eventos/')),
                ('categoria', models.CharField(choices=[('Feria', 'Feria / Exposición'), ('Taller', 'Taller Educativo o Creativo'), ('ExpoVenta', 'Expo-Venta'), ('Cultural', 'Presentación Cultural / Tradicional'), ('Otro', 'Otro')], default='Feria', max_length=30)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='circuitos.ciudad')),
                ('protagonista_organizador', models.ForeignKey(blank=True, help_text='Si es organizado por un protagonista', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_organizados', to='circuitos.protagonista')),
            ],
        ),
        migrations.CreateModel(
            name='PuntoInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('Cultural', 'Cultural'), ('Historico', 'Histórico'), ('Natural', 'Natural'), ('Gastronomico', 'Gastronómico'), ('Taller Artesanal', 'Taller Artesanal'), ('Hospedaje', 'Hospedaje'), ('Otro', 'Otro')], default='Cultural', max_length=30)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('imagen', models.ImageField(upload_to='puntos/imagenes/')),
                ('audio_guia', models.FileField(blank=True, help_text='Audio guía en MP3/WAV para la experiencia inmersiva', null=True, upload_to='puntos/audios/')),
                ('visita_virtual_url', models.URLField(blank=True, help_text='URL a recorrido 360° o video inmersivo', null=True)),
                ('saberes_populares', models.TextField(blank=True, help_text='Historias, saberes populares, leyendas o datos tradicionales', null=True)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de aparición en la ruta')),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='circuitos.circuitocreativo')),
            ],
            options={
                'verbose_name_plural': 'Puntos de Interés',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='protagonista',
            name='punto_interes_asociado',
            field=models.ForeignKey(blank=True, help_text='Punto de interés donde se ubica el negocio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protagonistas', to='circuitos.puntointeres'),
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveIntegerField(help_text='Puntuación de 1 a 5')),
                ('comentario', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('punto_interes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='circuitos.puntointeres')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'unique_together': {('user', 'punto_interes')},
            },
        ),
    ]
